version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27000:27017
    networks:
      - mydockernet
    volumes:
      - "app_mongo:/data/db"
  appserver:
    image: appserver:123
    container_name: appserver
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    networks:
      - mydockernet
    environment:
      - DEBUG=1
      - NODE_ENV=production
      - TEST=test123
      - DB_HOST=mongo
      - DB_PORT=27000
      - DB_NAME=sabil
      - JWT_SECRET=JWT_SECRETfsdfsdfsdsd3435353
      - IS_MONGODB_CLOUD_URL=false
      - JWT_EXPIRES_IN=3600
      - PORT=8008
    depends_on:
      - mongo
  appclient:
    image: appclient:123
    container_name: appclient
    build:
      context: ./client
      args:
        REACT_APP_API_URL: http://localhost:8008/api
        REACT_APP_ENV: production
      dockerfile: Dockerfile
    networks:
      - mydockernet
    environment:
      - REACT_APP_ENV=production
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_API_URL=http://localhost:8008/api
    ports:
      - 8001:8001
    depends_on:
      - appserver
networks:
  mydockernet:
    driver: bridge
volumes:
  app_mongo: null
