version: '3.8'
services:
  appserver:
    image: appserver:pi
    container_name: appserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    environment:
      - DEBUG=1
      - NODE_ENV=production
      - TEST=test123
      - DB_HOST=172.17.0.1
      - DB_PORT=27000
      - DB_NAME=murmur
      - JWT_SECRET=JWT_SECRETfsdfsdfsdsd3435353
      - JWT_EXPIRES_IN=3600
      - PORT=8008
      - IS_MONGODB_CLOUD_URL=false
      - MONGODB_CLOUD_URL=mongodb+srv://shakilhasan:sH1404087@cluster0.9r8bg.mongodb.net/murmur?retryWrites=true&w=majority
