version: '3.8'
services:
  appserver:
    image: appserver:pi
    container_name: appserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      - DEBUG=1
      - NODE_ENV=production
      - TEST=test123
      - DB_HOST=mongo
      - DB_PORT=20717
      - DB_NAME=sabil
      - JWT_SECRET=JWT_SECRETfsdfsdfsdsd3435353
      - JWT_EXPIRES_IN=3600
      - PORT=8002
      - IS_MONGODB_CLOUD_URL=false
      - MONGODB_CLOUD_URL=mongodb+srv://shakilhasan:sH1404087@cluster0.9r8bg.mongodb.net/sabil?retryWrites=true&w=majority
